language: scala
sudo: false

scala:
- 2.11.12
- 2.12.7

script:
- sbt ++$TRAVIS_SCALA_VERSION sparkSqlScalaPB/test

jobs:
  include:
    - name: "UDT generator"
      scala: 2.12
      script:
      - ./test_udt_gen.sh
