language: scala
sudo: false

# spark versions <=2.4 is only compatible with jdk8
jdk:
- openjdk8

scala:
- 2.12.10

script:

jobs:
  include:
    - name: "Test"
      scala: 2.12.10
      script:
      - sbt ++$TRAVIS_SCALA_VERSION sparkSqlScalaPB/test
    - name: "Formatting"
      scala: 2.12.10
      script:
      - sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

