language: scala
sudo: false

# spark versions <=2.4 is only compatible with jdk8
jdk:
- openjdk8

scala:
- 2.11.12
- 2.12.7

script:
- sbt ++$TRAVIS_SCALA_VERSION sparkSqlScalaPB/test

jobs:
  include:
    - name: "UDT generator"
      scala: 2.12
      script:
      - ./test_udt_gen.sh
